"""Executive summary report generator."""

from __future__ import annotations

from collections import Counter
from datetime import datetime, timezone

from gws_inspector.models import ComplianceFinding, GWSData
from gws_inspector.output import OutputManager
from gws_inspector.reporters import register_reporter
from gws_inspector.reporters.base import ReportGenerator

_FRAMEWORKS = (
    "FedRAMP",
    "CMMC",
    "SOC2",
    "DISA STIG",
    "IRAP",
    "ISMAP",
    "PCI-DSS",
    "CIS",
)


@register_reporter
class ExecutiveReportGenerator(ReportGenerator):
    """Generate a compliance executive summary."""

    name = "executive"
    display_name = "Executive Summary"

    def generate(
        self,
        findings: list[ComplianceFinding],
        data: GWSData,
        output: OutputManager,
    ) -> None:
        ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        status_counts = Counter(f.status for f in findings)
        severity_counts = Counter(f.severity for f in findings)
        framework_counts: dict[str, Counter[str]] = {}
        for f in findings:
            framework_counts.setdefault(f.framework, Counter())
            framework_counts[f.framework][f.status] += 1

        total_users = len(data.users)
        total_admins = len(data.super_admins) + len(data.delegated_admins)
        total_groups = len(data.groups)

        critical_findings = sorted(
            [f for f in findings if f.status == "fail"],
            key=lambda f: ("critical", "high", "medium", "low", "info").index(f.severity)
            if f.severity in ("critical", "high", "medium", "low", "info")
            else 99,
        )[:5]

        manual_items = [f for f in findings if f.status == "manual"]

        lines: list[str] = []
        _a = lines.append

        _a("# GWS Compliance Executive Summary")
        _a("")
        _a(f"**Generated:** {ts}")
        _a(f"**Domain:** {data.domain}")
        _a("")
        _a("## Overview")
        _a("")
        _a("This report summarises the compliance posture of the Google Workspace environment")
        _a(f"against **{len(_FRAMEWORKS)} frameworks**: {', '.join(_FRAMEWORKS)}.")
        _a("")
        _a("## Key Metrics")
        _a("")
        _a("| Metric | Value |")
        _a("|--------|-------|")
        _a(f"| Total Users | {total_users} |")
        _a(f"| Admin Users | {total_admins} |")
        _a(f"| Super Admins | {len(data.super_admins)} |")
        _a(f"| Delegated Admins | {len(data.delegated_admins)} |")
        _a(f"| Groups | {total_groups} |")
        _a(f"| Org Units | {len(data.org_units)} |")
        _a("")
        _a("## Compliance Results Summary")
        _a("")
        _a("| Status | Count |")
        _a("|--------|-------|")
        for status in ("pass", "fail", "manual", "not_applicable", "error"):
            _a(f"| {status.replace('_', ' ').title()} | {status_counts.get(status, 0)} |")
        _a(f"| **Total** | **{len(findings)}** |")
        _a("")
        _a("### By Severity")
        _a("")
        _a("| Severity | Count |")
        _a("|----------|-------|")
        for sev in ("critical", "high", "medium", "low", "info"):
            _a(f"| {sev.title()} | {severity_counts.get(sev, 0)} |")
        _a("")

        _a("## Top 5 Critical Findings")
        _a("")
        if critical_findings:
            for i, f in enumerate(critical_findings, 1):
                _a(f"### {i}. [{f.severity.upper()}] {f.title}")
                _a("")
                _a(f"- **Framework:** {f.framework}")
                _a(f"- **Control:** {f.control_id}")
                _a(f"- **Details:** {f.comments}")
                _a("")
        else:
            _a("No failing controls detected. All assessed controls passed.")
            _a("")

        _a("## Results by Framework")
        _a("")
        _a("| Framework | Pass | Fail | Manual | N/A | Error | Total |")
        _a("|-----------|------|------|--------|-----|-------|-------|")
        for fw in _FRAMEWORKS:
            fc = framework_counts.get(fw, Counter())
            total = sum(fc.values())
            _a(
                f"| {fw} | {fc.get('pass', 0)} | {fc.get('fail', 0)} "
                f"| {fc.get('manual', 0)} | {fc.get('not_applicable', 0)} "
                f"| {fc.get('error', 0)} | {total} |"
            )
        _a("")

        _a("## Manual Verification Items")
        _a("")
        if manual_items:
            _a(f"**{len(manual_items)}** controls require manual verification:")
            _a("")
            for f in manual_items:
                _a(f"- **[{f.framework}] {f.control_id}**: {f.title}")
        else:
            _a("No manual verification items identified.")
        _a("")

        _a("---")
        _a(f"*Report generated by gws-inspector on {ts}*")

        output.save_markdown("\n".join(lines), "compliance", "executive_summary.md")
