"""Unified compliance matrix report generator."""

from __future__ import annotations

from datetime import datetime, timezone

from gws_inspector.models import ComplianceFinding, GWSData
from gws_inspector.output import OutputManager
from gws_inspector.reporters import register_reporter
from gws_inspector.reporters.base import ReportGenerator

_FRAMEWORK_COLUMNS = (
    "FedRAMP",
    "CMMC",
    "SOC2",
    "DISA STIG",
    "IRAP",
    "ISMAP",
    "PCI-DSS",
    "CIS",
)

_STATUS_SYMBOL = {
    "pass": "PASS",
    "fail": "FAIL",
    "manual": "MANUAL",
    "not_applicable": "N/A",
    "error": "ERROR",
}

_CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "Authentication": ["mfa", "2sv", "two-step", "two_step", "authentication", "login", "sign-in", "phishing"],
    "Password": ["password", "credential"],
    "Session": ["session", "timeout", "duration", "idle"],
    "Account Management": ["admin", "privilege", "role", "account", "user", "onboard", "offboard", "suspend"],
    "Monitoring": ["audit", "log", "monitor", "alert", "event", "report"],
    "Manual": [],
}


def _categorise(finding: ComplianceFinding) -> str:
    """Assign a finding to a section category based on keyword matching."""
    if finding.status == "manual":
        return "Manual"
    text = f"{finding.title} {finding.control_id} {finding.comments}".lower()
    for category, keywords in _CATEGORY_KEYWORDS.items():
        if category == "Manual":
            continue
        if any(kw in text for kw in keywords):
            return category
    return "Account Management"


@register_reporter
class MatrixReportGenerator(ReportGenerator):
    """Generate a unified cross-framework compliance matrix."""

    name = "matrix"
    display_name = "Unified Compliance Matrix"

    def generate(
        self,
        findings: list[ComplianceFinding],
        data: GWSData,
        output: OutputManager,
    ) -> None:
        ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

        # Build lookup: (framework, control_id) -> status
        fw_lookup: dict[str, dict[str, str]] = {fw: {} for fw in _FRAMEWORK_COLUMNS}
        for f in findings:
            if f.framework in fw_lookup:
                fw_lookup[f.framework][f.control_id] = f.status

        # Group findings by category
        categorised: dict[str, list[ComplianceFinding]] = {}
        for f in findings:
            cat = _categorise(f)
            categorised.setdefault(cat, [])
            categorised[cat].append(f)

        lines: list[str] = []
        _a = lines.append

        _a("# Unified Compliance Matrix")
        _a("")
        _a(f"**Generated:** {ts}")
        _a(f"**Domain:** {data.domain}")
        _a("")
        _a("This matrix maps security controls across all assessed compliance frameworks,")
        _a("showing the current status of each check.")
        _a("")
        _a("**Legend:** PASS | FAIL | MANUAL | N/A | ERROR | `-` (not mapped)")
        _a("")

        header = "| Check | " + " | ".join(_FRAMEWORK_COLUMNS) + " | Status |"
        separator = "|" + "|".join(["-------"] * (len(_FRAMEWORK_COLUMNS) + 2)) + "|"

        section_order = [
            "Authentication",
            "Password",
            "Session",
            "Account Management",
            "Monitoring",
            "Manual",
        ]

        for section in section_order:
            section_findings = categorised.get(section, [])
            if not section_findings:
                continue

            _a(f"## {section}")
            _a("")
            _a(header)
            _a(separator)

            # De-duplicate by title for cross-framework display
            seen_titles: dict[str, dict[str, str]] = {}
            title_status: dict[str, str] = {}
            for f in section_findings:
                key = f.title
                if key not in seen_titles:
                    seen_titles[key] = {}
                    title_status[key] = f.status
                seen_titles[key][f.framework] = _STATUS_SYMBOL.get(f.status, "-")
                # Worst-case status wins for the overall column
                if f.status == "fail":
                    title_status[key] = "fail"
                elif f.status == "manual" and title_status[key] not in ("fail",):
                    title_status[key] = "manual"

            for title, fw_map in seen_titles.items():
                cols = " | ".join(fw_map.get(fw, "-") for fw in _FRAMEWORK_COLUMNS)
                overall = _STATUS_SYMBOL.get(title_status.get(title, ""), "-")
                _a(f"| {title} | {cols} | {overall} |")

            _a("")

        _a("---")
        _a(f"*Matrix generated by gws-inspector on {ts}*")

        output.save_markdown("\n".join(lines), "compliance", "unified_compliance_matrix.md")
